# Generated by Django 4.2.14 on 2024-08-27 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True,
                 upload_to='assets/frontend/images/instructors/')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.DurationField(
                    help_text='Duração da aula (ex. 1:30:00 para 1 hora e meia)')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (
                    2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('time', models.TimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='regular_instructor', to='scheduling.instructor')),
                ('substitute_instructors', models.ManyToManyField(
                    related_name='substitute_instructors', to='scheduling.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimeException',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_time', models.TimeField()),
                ('fitness_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='scheduling.weeklyclass')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('fitness_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='scheduling.weeklyclass')),
                ('instructor', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.instructor')),
                ('participants', models.ManyToManyField(
                    blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Booking',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True,
        #          primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('canceled', models.BooleanField(default=False)),
        #         ('canceled_at', models.DateTimeField(blank=True, null=True)),
        #         ('fitness_class', models.ForeignKey(
        #             on_delete=django.db.models.deletion.CASCADE, to='scheduling.weeklyclass')),
        #         ('user', models.ForeignKey(
        #             on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
