# Generated by Django 4.2.16 on 2024-09-21 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
