# Generated by Django 4.2.16 on 2024-10-08 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_classsession_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='session_identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
