# Generated by Django 4.2.16 on 2024-10-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_classsession_session_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_session', to='scheduling.weeklyclass'),
        ),
    ]
