# Generated by Django 4.2.13 on 2024-05-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup_show_about_us_sitesetup_show_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_training_categories',
            field=models.BooleanField(default=True),
        ),
    ]
