# Generated by Django 4.2.16 on 2024-09-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_alter_userprofile_client_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_code',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
