# Generated by Django 4.2.16 on 2024-09-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_userprofile_reset_password_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reset_password_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
