# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_alter_userprofile_reset_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
