# Generated by Django 4.2.16 on 2024-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_userprofile_reset_password_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
