# Generated by Django 4.2.13 on 2024-05-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFieldOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=65, null=True)),
                ('image', models.ImageField(upload_to='assets/frontend/images/section_1/top_images/')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default='2024-01-01', verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Image field 1',
                'verbose_name_plural': 'Image field 1',
            },
        ),
        migrations.CreateModel(
            name='TextField1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_1', models.CharField(max_length=15)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default='2024-01-01', verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 1',
                'verbose_name_plural': 'Text field 1',
            },
        ),
        migrations.CreateModel(
            name='TextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_2', models.CharField(max_length=15)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default='2024-01-01', verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 2',
                'verbose_name_plural': 'Text field 2',
            },
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01', verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='active_image_filed_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.imagefieldone'),
        ),
    ]
