# Generated by Django 4.2.13 on 2024-05-22 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_alter_imagefieldone_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFieldThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=65, null=True)),
                ('image', models.ImageField(upload_to='assets/frontend/images/section_3/images/')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Image field 3',
                'verbose_name_plural': 'Image field 3',
            },
        ),
        migrations.CreateModel(
            name='ImageFieldTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=65, null=True)),
                ('image', models.ImageField(upload_to='assets/frontend/images/section_2/images/')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Image field 2',
                'verbose_name_plural': 'Image field 2',
            },
        ),
        migrations.CreateModel(
            name='TextFieldFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_5', models.CharField(max_length=20)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 5',
                'verbose_name_plural': 'Text field 5',
            },
        ),
        migrations.CreateModel(
            name='TextFieldFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_4', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 4',
                'verbose_name_plural': 'Text field 4',
            },
        ),
        migrations.CreateModel(
            name='TextFieldOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_1', models.CharField(max_length=30)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 1',
                'verbose_name_plural': 'Text field 1',
            },
        ),
        migrations.CreateModel(
            name='TextFieldSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_7', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 7',
                'verbose_name_plural': 'Text field 7',
            },
        ),
        migrations.CreateModel(
            name='TextFieldSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_6', models.CharField(max_length=30)),
                ('url_or_path', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 6',
                'verbose_name_plural': 'Text field 6',
            },
        ),
        migrations.CreateModel(
            name='TextFieldthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_3', models.CharField(max_length=30)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 3',
                'verbose_name_plural': 'Text field 3',
            },
        ),
        migrations.CreateModel(
            name='TextFieldTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_2', models.CharField(max_length=30)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 2',
                'verbose_name_plural': 'Text field 2',
            },
        ),
        migrations.DeleteModel(
            name='TextField1',
        ),
        migrations.DeleteModel(
            name='TextField2',
        ),
    ]
