# Generated by Django 4.2.13 on 2024-05-24 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_imagefieldthree_imagefieldtwo_textfieldfive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='assets/frontend/images/section_5/cards/', verbose_name='Logo')),
                ('price', models.CharField(blank=True, max_length=30, null=True, verbose_name='Preço')),
                ('span', models.CharField(max_length=30)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='ImageFieldFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=65, null=True)),
                ('image', models.ImageField(upload_to='assets/frontend/images/section_6/images/')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Image field 4',
                'verbose_name_plural': 'Image field 4',
            },
        ),
        migrations.CreateModel(
            name='PriceCardIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='assets/frontend/images/section_5/pricing_icons/', verbose_name='Icone')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Icone de preço',
                'verbose_name_plural': 'Icones de preço',
            },
        ),
        migrations.CreateModel(
            name='PricingOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.CharField(max_length=35)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ofertas de preço',
                'verbose_name_plural': 'Ofertas de preço',
            },
        ),
        migrations.CreateModel(
            name='SectionFiveHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 8',
                'verbose_name_plural': 'Text field 8',
            },
        ),
        migrations.CreateModel(
            name='SectionSixHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 9',
                'verbose_name_plural': 'Text field 9',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='assets/frontend/images/section_9/icons/', verbose_name='Icone')),
                ('text_field_12', models.CharField(max_length=50)),
                ('text_field_13', models.CharField(max_length=50)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='TextFieldEleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_11', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 11',
                'verbose_name_plural': 'Text field 11',
            },
        ),
        migrations.CreateModel(
            name='TextFieldTen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_10', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Text field 10',
                'verbose_name_plural': 'Text field 10',
            },
        ),
        migrations.CreateModel(
            name='VideoOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=65, null=True)),
                ('video', models.FileField(upload_to='assets/frontend/videos/section_8/videos/')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Video 1',
                'verbose_name_plural': 'Video 1',
            },
        ),
        migrations.CreateModel(
            name='OffersIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.pricecardicons')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.card')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.pricingoffers')),
            ],
            options={
                'verbose_name': 'Icone de ofertas',
                'verbose_name_plural': 'Icones de ofertas',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='Ofertas',
            field=models.ManyToManyField(blank=True, to='user_dashboard.offersicons', verbose_name='Ofertas'),
        ),
    ]
