# Generated by Django 4.2.13 on 2024-05-27 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_card_imagefieldfour_pricecardicons_pricingoffers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=65, null=True, verbose_name='Titulo')),
                ('video', models.FileField(blank=True, null=True, upload_to='assets/frontend/videos/section_8/videos/', verbose_name='Video')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Video 1',
                'verbose_name_plural': 'Video 1',
            },
        ),
        migrations.CreateModel(
            name='SectionNine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='assets/frontend/images/section_9/icons/', verbose_name='Icone')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do serviço')),
                ('text_field_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='campo 1')),
                ('text_field_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='campo 2')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='SectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('title', models.CharField(blank=True, max_length=65, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_1/top_images/', verbose_name='Imagem de Topo')),
                ('text_field_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header 1')),
                ('text_field_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header 2')),
            ],
            options={
                'verbose_name': 'Seção 1',
                'verbose_name_plural': 'Seção 1',
            },
        ),
        migrations.CreateModel(
            name='SectionSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_6/images/', verbose_name='Imagem de Secção 6')),
                ('paragraph_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paragrafo 1')),
                ('paragraph_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paragrafo 2')),
            ],
            options={
                'verbose_name': 'Seção 6',
                'verbose_name_plural': 'Seção 6',
            },
        ),
        migrations.CreateModel(
            name='SectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_3/images/', verbose_name='Imagem 1 de Secção 3')),
                ('text_field_5', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header da foto 1')),
                ('url_or_path_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL ou caminho da foto 1')),
                ('text_field_6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paragrafo da foto 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_3/images/', verbose_name='Imagem 2 de Secção 3')),
                ('text_field_7', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header da foto 2')),
                ('url_or_path_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL ou caminho da foto 2')),
                ('text_field_8', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paragrafo da foto 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_3/images/', verbose_name='Imagem 3 de Secção 3')),
                ('text_field_9', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header da foto 3')),
                ('url_or_path_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL ou caminho da foto 3')),
                ('text_field_10', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paragrafo da foto 3')),
            ],
            options={
                'verbose_name': 'Seção 3',
                'verbose_name_plural': 'Seção 3',
            },
        ),
        migrations.CreateModel(
            name='SectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('text_field_3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Header 1')),
                ('text_field_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Header 2')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_2/images/', verbose_name='Imagem 1 de Secção 2')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_2/images/', verbose_name='Imagem 2 de Secção 2')),
            ],
            options={
                'verbose_name': 'Seção 2',
                'verbose_name_plural': 'Seção 2',
            },
        ),
        migrations.DeleteModel(
            name='ImageFieldFour',
        ),
        migrations.DeleteModel(
            name='ImageFieldThree',
        ),
        migrations.DeleteModel(
            name='ImageFieldTwo',
        ),
        migrations.DeleteModel(
            name='SectionSixHeader',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='TextFieldEleven',
        ),
        migrations.DeleteModel(
            name='TextFieldFive',
        ),
        migrations.DeleteModel(
            name='TextFieldFour',
        ),
        migrations.DeleteModel(
            name='TextFieldOne',
        ),
        migrations.DeleteModel(
            name='TextFieldSeven',
        ),
        migrations.DeleteModel(
            name='TextFieldSix',
        ),
        migrations.DeleteModel(
            name='TextFieldTen',
        ),
        migrations.DeleteModel(
            name='TextFieldthree',
        ),
        migrations.DeleteModel(
            name='TextFieldTwo',
        ),
        migrations.RemoveField(
            model_name='userdashboard',
            name='active_image_filed_1',
        ),
        migrations.DeleteModel(
            name='VideoOne',
        ),
        migrations.RemoveField(
            model_name='card',
            name='Ofertas',
        ),
        migrations.RemoveField(
            model_name='offersicons',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='pricingoffers',
            name='offers',
        ),
        migrations.AddField(
            model_name='card',
            name='Offers',
            field=models.ManyToManyField(blank=True, null=True, to='user_dashboard.offersicons', verbose_name='Ofertas'),
        ),
        migrations.AddField(
            model_name='offersicons',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.pricingoffers'),
        ),
        migrations.AddField(
            model_name='pricingoffers',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Nome da Oderta'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_5/cards/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome do Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='card',
            name='span',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Span'),
        ),
        migrations.AlterField(
            model_name='offersicons',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.pricecardicons', verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='pricecardicons',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_5/pricing_icons/', verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='sectionfiveheader',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Header 1'),
        ),
        migrations.DeleteModel(
            name='ImageFieldOne',
        ),
        migrations.DeleteModel(
            name='UserDashboard',
        ),
    ]
