# Generated by Django 4.2.13 on 2024-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_sectioneight_sectionnine_sectionone_sectionsix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Offers',
            field=models.ManyToManyField(blank=True, to='user_dashboard.offersicons', verbose_name='Ofertas'),
        ),
    ]
