# Generated by Django 4.2.13 on 2024-05-28 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0007_alter_card_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Offers',
        ),
        migrations.RemoveField(
            model_name='sectionone',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='text_field_10',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='text_field_7',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='text_field_8',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='text_field_9',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='url_or_path_1',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='url_or_path_2',
        ),
        migrations.RemoveField(
            model_name='sectionthree',
            name='url_or_path_3',
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='offersicons',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='pricecardicons',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Nome do Icone'),
        ),
        migrations.AddField(
            model_name='pricecardicons',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='pricingoffers',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='sectioneight',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visível na página'),
        ),
        migrations.AddField(
            model_name='sectioneight',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do video'),
        ),
        migrations.AddField(
            model_name='sectioneight',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='sectionfiveheader',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='sectionnine',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='sectionthree',
            name='url_or_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL ou caminho da foto 1'),
        ),
        migrations.AddField(
            model_name='card',
            name='offers',
            field=models.ManyToManyField(blank=True, to='user_dashboard.offersicons', verbose_name='Ofertas'),
        ),
    ]
