# Generated by Django 4.2.13 on 2024-05-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0008_remove_card_offers_remove_sectionone_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Seção 5 - Card', 'verbose_name_plural': 'Seção 5 - Cards'},
        ),
        migrations.AlterModelOptions(
            name='offersicons',
            options={'verbose_name': 'Seção 5 - Icone de ofertas', 'verbose_name_plural': 'Seção 5 - Icones de ofertas'},
        ),
        migrations.AlterModelOptions(
            name='pricecardicons',
            options={'verbose_name': 'Seção 5 - Icone de preço', 'verbose_name_plural': 'Seção 5 - Icones de preço'},
        ),
        migrations.AlterModelOptions(
            name='pricingoffers',
            options={'verbose_name': 'Seção 5 - Ofertas de preço', 'verbose_name_plural': 'Seção 5 - Ofertas de preço'},
        ),
        migrations.AlterModelOptions(
            name='sectioneight',
            options={'verbose_name': 'Seção 8', 'verbose_name_plural': 'Seção 8'},
        ),
        migrations.AlterModelOptions(
            name='sectionfiveheader',
            options={'verbose_name': 'Seção 5 - Header', 'verbose_name_plural': 'Seção 5 - Headers'},
        ),
        migrations.AlterModelOptions(
            name='sectionnine',
            options={'verbose_name': 'Seção 9', 'verbose_name_plural': 'Seção 9'},
        ),
    ]
