# Generated by Django 4.2.13 on 2024-06-19 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0011_remove_sectionthree_url_or_path_sectionthree_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_4/gallery/', verbose_name='Imagem')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visível na página')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Seção 4 - Galeria',
                'verbose_name_plural': 'Seção 4 - Galeria',
            },
        ),
    ]
