# Generated by Django 4.2.13 on 2024-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0012_sectionfour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfour',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag'),
        ),
    ]
