# Generated by Django 4.2.13 on 2024-06-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0014_sectionfour_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionone',
            name='image',
        ),
        migrations.AddField(
            model_name='sectionone',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_1/top_images/', verbose_name='Imagem de Topo'),
        ),
        migrations.AddField(
            model_name='sectionone',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_1/top_images/', verbose_name='Imagem de Topo 2'),
        ),
    ]
