# Generated by Django 4.2.14 on 2024-08-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0016_alter_pricingoffers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offersicons',
            name='name',
        ),
        migrations.AlterField(
            model_name='offersicons',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.pricingoffers', verbose_name='Oferta'),
        ),
    ]
