# Generated by Django 4.2.14 on 2024-08-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0017_remove_offersicons_name_alter_offersicons_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioneight',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sectioneight',
            name='video',
        ),
        migrations.AddField(
            model_name='sectioneight',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL do video'),
        ),
    ]
