# Generated by Django 4.2.14 on 2024-08-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0018_remove_sectioneight_title_remove_sectioneight_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnine',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='assets/frontend/images/section_9/icons/', verbose_name='Icone'),
        ),
    ]
