# Generated by Django 4.2.14 on 2024-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0020_tiposdeaulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdeaulas',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordem'),
        ),
    ]
