# Generated by Django 4.2.14 on 2024-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0021_tiposdeaulas_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdeaulas',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visível na página'),
        ),
    ]
