# Generated by Django 4.2.14 on 2024-08-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0022_tiposdeaulas_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposdeaulas',
            options={'verbose_name': 'Tipo de Aula', 'verbose_name_plural': 'Tipos de Aulas'},
        ),
    ]
