# Generated by Django 4.2.14 on 2024-08-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0023_alter_tiposdeaulas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdeaulas',
            name='image',
            field=models.ImageField(help_text='Escolha a Imagem.', upload_to='assets/frontend/images/tipos_de_aulas'),
        ),
    ]
