# Generated by Django 4.2.16 on 2024-09-25 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import physical_evaluations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('ECTOMORFO', 'Ectomorfo'), ('MESOMORFO', 'Mesomorfo'), ('ENDOMORFO', 'Endomorfo')], max_length=10, unique=True)),
                ('ideal_weight_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ideal_weight_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ideal_body_fat_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ideal_body_fat_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_water_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_water_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle_mass_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle_mass_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fitness_level_min', models.IntegerField()),
                ('fitness_level_max', models.IntegerField()),
                ('calories_burned_min', models.IntegerField()),
                ('calories_burned_max', models.IntegerField()),
                ('metabolic_age_min', models.IntegerField()),
                ('metabolic_age_max', models.IntegerField()),
                ('bone_mass_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bone_mass_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('visceral_fat_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('visceral_fat_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Body Type',
                'verbose_name_plural': 'Body Types',
            },
        ),
        migrations.CreateModel(
            name='PhysicalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('belly_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leg_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arm_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_water_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle_mass_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fitness_level', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('metabolic_age', models.IntegerField()),
                ('bone_mass', models.DecimalField(decimal_places=2, max_digits=4)),
                ('visceral_fat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_evaluations.bodytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physical Evaluation',
                'verbose_name_plural': 'Physical Evaluations',
            },
        ),
        migrations.CreateModel(
            name='PhysicalEvaluationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_front', models.ImageField(upload_to=physical_evaluations.models.user_directory_path)),
                ('image_side', models.ImageField(upload_to=physical_evaluations.models.user_directory_path)),
                ('image_back', models.ImageField(upload_to=physical_evaluations.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='physical_evaluations.physicalevaluation')),
            ],
            options={
                'verbose_name': 'Physical Evaluation Image',
                'verbose_name_plural': 'Physical Evaluation Images',
            },
        ),
    ]
