# Generated by Django 4.2.16 on 2024-09-25 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physical_evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatingHabitsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eating Habits Question',
                'verbose_name_plural': 'Eating Habits Questions',
            },
        ),
        migrations.CreateModel(
            name='HealthStateQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health State Question',
                'verbose_name_plural': 'Health State Questions',
            },
        ),
        migrations.CreateModel(
            name='HealthStateAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical_evaluations.healthstatequestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_state_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health State Answer',
                'verbose_name_plural': 'Health State Answers',
            },
        ),
        migrations.CreateModel(
            name='EatingHabitsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical_evaluations.eatinghabitsquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eating_habits_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eating Habits Answer',
                'verbose_name_plural': 'Eating Habits Answers',
            },
        ),
    ]
