# Generated by Django 4.2.16 on 2024-10-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
