# Generated by Django 4.2.16 on 2024-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
