# Generated by Django 4.2.16 on 2024-10-31 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='month_year',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='billing.invoice'),
        ),
    ]
